name: Tutorial Tester
description: Runs Playwright tests to test tutorials and guides.
inputs:
  tutorial-paths:
    description: Array of paths for the test to look at, excluding the root path. (e.g. '["hello-world", "advanced/guide"]')
    required: true
  config-path:
    description: Filepath of the test configuration file. Expects an IStepConfig type to be exported as default in the file.
    required: true
  folder-name:
    description: Name of the main project folder created in the tutorial.
    required: true
  custom-timeout:
    description: Number of milliseconds to wait for the test to complete. Defaults to what's in your playwright config.
    required: false
  wait-time:
    description: Number of milliseconds to wait before starting the test. Defaults to 45 seconds.
    required: false
  mm-wallet:
    description: True or false to indicate if the test needs to use a Metamask wallet. Defaults to false.
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Install action dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        bun install --frozen-lockfile
        bun playwright install chromium --with-deps
    - name: Execute test
      shell: bash
      env:
        DIR_PATH: ${{ github.workspace }}
        CONFIG_PATH: ${{ inputs.config-path }}
        CUSTOM_TIMEOUT: ${{ inputs.custom-timeout }}
        FOLDER_NAME: ${{ inputs.folder-name }}
        WAIT_TIME: ${{ inputs.wait-time }}
        TUTORIAL_PATHS: >-
          {"paths":${{ inputs.tutorial-paths }}}
      if: ${{ inputs.mm-wallet == 'false' }}
      working-directory: ${{ github.action_path }}
      run: |
        export TERM=xterm-256color
        export COLUMNS=80
        export LINES=24
        set -euo pipefail
        xvfb-run bun test:headful tests/test.spec.ts
    # - name: Execute test with metamask
    #   if: ${{ inputs.mm-wallet == 'true' }}
    #   working-directory: ${{ github.action_path }}
    #   run: |
    #     export TERM=xterm-256color
    #     export COLUMNS=80
    #     export LINES=24
    #     export TUTORIAL_PATHS=${{ inputs.tutorial-paths }}
    #     export CONFIG_PATH=${{ inputs.config-path }}
    #     export CUSTOM_TIMEOUT=${{ inputs.custom-timeout }}
    #     set -euo pipefail
    #     xvfb-run bun test:headful tests/mm-test.spec.ts
